### ISSUE TITLE
BNOptimizer not found 

### ISSUE THREAD

**Issue by zhyj3038** [violet17/yolov3-channel-pruning#1]
hi, thanks very much for you great work. but when I run you code , an error occured,  NameError: name 'BNOptimizer' is not defined.    there is no definition of  it!!

**Comment by violet17** [comment]
change `BNOptimizer.updateBN(sr_flag, model.module_list, opt.s, prune_idx)` in Line 142 to `updateBN(sr_flag, model.module_list, opt.s, prune_idx)`

**Comment by PiseyYou** [comment]
I follow your suggestion, it work. Great job.
